# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AYM_Assignment' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AYM_Assignment
  # Core
  pod 'Moya/RxSwift', '~> 11.0'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'

  # UI
  pod 'Cosmos'#, '~> 16.0'
  pod 'AlamofireImage'

  target 'AYM_AssignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
